
/* IMPORT */

import os from 'node:os';

/* MAIN */

const DEBOUNCE = 300;

const DEPTH = 20;

const LIMIT = 10_000_000;

const PLATFORM = os.platform ();

const IS_LINUX = ( PLATFORM === 'linux' );

const IS_MAC = ( PLATFORM === 'darwin' );

const IS_WINDOWS = ( PLATFORM === 'win32' );

const NODE_VERSION_PARTS = process.versions.node.split ( '.' ).map ( Number );

const NODE_VERSION_MAJOR = NODE_VERSION_PARTS[0];

const NODE_VERSION_MINOR = NODE_VERSION_PARTS[1];

const HAS_NATIVE_RECURSION = IS_MAC || IS_WINDOWS || ( IS_LINUX && ( ( NODE_VERSION_MAJOR === 20 && NODE_VERSION_MINOR >= 13 ) || ( NODE_VERSION_MAJOR === 22 && NODE_VERSION_MINOR >= 1 ) || NODE_VERSION_MAJOR > 22 ) );

const POLLING_INTERVAL = 3000;

const POLLING_TIMEOUT = 20000;

const RENAME_TIMEOUT = 1250;

/* EXPORT */

export {DEBOUNCE, DEPTH, LIMIT, HAS_NATIVE_RECURSION, IS_LINUX, IS_MAC, IS_WINDOWS, PLATFORM, POLLING_INTERVAL, POLLING_TIMEOUT, RENAME_TIMEOUT};
